### PR TITLE
Remove Powerstrip demonstration

### PR DESCRIPTION
**Pull request by robbrockbank**
This PR is an incremental update to remove powerstrip from the calico-docker repo.

A side effect of this is:
-  The removal of the Orchestrator.md guide
-  The removal of the Swarm demo

Both of these were focussed on the powerstrip demo.  New issues have been raised to re-instate these two documents focussed on libnetwork, or default networking.

### CODE REVIEW

**Comment by robbrockbank** [comment]
Fixes #546

**Comment by tomdee** [comment]
I'll review/merge this as part of our next release

**Comment by TrimBiggs** [comment]
You will need to remove the reference to Orchestrators.md in the FAQ also.

**Comment by tomdee** [comment]
LGTM

**Pull request merged**
