### PR TITLE
Add VPC creation instructions to AWS doc

### PR DESCRIPTION
**Pull request by TrimBiggs**

### CODE REVIEW

**Comment by tomdee** [comment]
@TrimBiggs What's your plan for getting this merged?

**Comment by TrimBiggs** [comment]
@tomdee I'll be updating this PR soon with some additional info I've found, then looking for a review.

**Comment by TrimBiggs** [comment]
Fixes #490

**Comment by spikecurtis** [comment]
LGTM

**Comment by TrimBiggs** [comment]
Fixes #490

**Pull request merged**
