### PR TITLE
Libnetwork ux changes no coreos

### PR DESCRIPTION
**Pull request by robbrockbank**
Libnetwork UX changes for demos - with coreOS demos removed

### CODE REVIEW

**Comment by tomdee** [comment]
Can you squash

**Comment by tomdee** [comment]
LGTM - but we'll need to do a release of libnetwork and calico-docker before we can merge this.

**Comment by tomdee** [comment]
@robbrockbank  You gonna close this?

**Comment by robbrockbank** [comment]
Obsolete.  Now included in release branch

**Pull request closed without merging**
