### PR TITLE
Release ips on endpoints found during node stop

### PR DESCRIPTION
**Pull request by L-MA**
Fixes issue #519

### CODE REVIEW

**Comment by caseydavenport** [comment]
What is the status of this PR?

**Comment by tomdee** [comment]
@robbrockbank

**Comment by robbrockbank** [comment]
Yup - will get to this in the next day or two.  Currently mulling over the broader implications / rework of calico node stop.  Also, this fix ties in with a related PR in libcalico that I think should probably be combined in some way.  Need to have a little more detailed think about the design here.

**Comment by robbrockbank** [comment]
Closing this PR - but this will be revisited during a rework of the node stop command

**Pull request closed without merging**
